# Generated by Django 5.2.8 on 2025-11-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_reforce_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default=1, max_length=128, verbose_name='Имя клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.CharField(default=1, max_length=128, verbose_name='Фамилия клиента'),
            preserve_default=False,
        ),
    ]
