# Generated by Django 5.2.8 on 2025-11-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_name_customuser_phone_customuser_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='chats',
        ),
        migrations.AddField(
            model_name='customuser',
            name='servers',
            field=models.ManyToManyField(blank=True, to='app.server', verbose_name='Серверы пользователя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reforce_password',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Точка для восстановления пароля'),
        ),
        migrations.AlterField(
            model_name='server',
            name='buy_date',
            field=models.DateField(verbose_name='Дата покупки/продления сервера'),
        ),
    ]
