# Generated by Django 5.2.8 on 2025-11-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_customuser_chats_customuser_servers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='buy_date',
            field=models.DateTimeField(verbose_name='Дата покупки/продления сервера'),
        ),
    ]
